### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by seuaCoder** [loloof64/ChessPgnReviserNodeGui#1]
I'm trying to install this with yarn install --ignore-engines but it doesn't work

`Node.js v20.2.0
error Command failed with exit code 1.`

**Comment by loloof64** [comment]
Hi ! May I ask you why do you add the flag `--ignore-engines` ?
Also this project is far from complete. It was just a toy project, that I gave up some times ago.

**Comment by seuaCoder** [comment]
Hi,

because it's say that my node version (20) is not supported

**Comment by loloof64** [comment]
Ok.

Anyway, this is an old toy project : there's no real implementation of the game.
Also I ended writing code for it 4 years ago (hence your issue with NodeJs I think)

**Comment by seuaCoder** [comment]
Ok no problems. I was just looking for an app to train from custom pgn puzzles and i came across this.

**Comment by loloof64** [comment]
You can try [this one](https://github.com/loloof64/ChessPgnReviser/releases/tag/v0.1.90) : it is complete.
You can find an exe version for Windows, or an AppImage version if you're targetting linux.

**Comment by seuaCoder** [comment]
Thank you
